version: '3.3'
services:
  test:
    build: ./Dockerfile.dev
    env_file: .env
    volumes:
      - .:/package

    command: pytest /package/tests

  bot:
    build: .
    env_file: .env
    command: lasttip
