version: '3.3'
services:
  flask-app:
    env_file:
      - .env
    build: flask-app
    restart: always
    ports:
      - '8000:8000'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:8000/flask-health-check || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app

  telegram-bot:
    depends_on:
      - flask-app
    env_file:
      - .env
    environment:
      - LASTTIP_API_URL=http://nginx-proxy:80
    build: telegram-bot
    restart: always
    ports:
      - '8443:8443'
      - '8444:80'
    command: python3 telegram_bot.py 

  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - "8181:80"
    depends_on:
      - flask-app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:80/health-check || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
