version: '3.3'
services:
  lasttip:
    build: .
    image: lasttip
    env_file: .env
    volumes:
      - .:/app/
    command: python3 /app/telegram-bot.py
    env_file: .env

  testing:
    build: .
    env_file: .env
    volumes:
      - .:/app/
    command: python3 spotify.py